USE MASTER

DROP DATABASE FABRICA
GO
CREATE DATABASE FABRICA
GO
USE FABRICA
GO
CREATE TABLE CATEGORIAS(
	ID INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL
)
GO
CREATE TABLE MATERIALES(
	ID INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL
)
GO
CREATE TABLE TAREAS(
	ID INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL
)
GO
CREATE TABLE PEDIDOS(
    ID BIGINT NOT NULL PRIMARY KEY IDENTITY (1, 1),
    IDCLIENTE INT NOT NULL,
    IDPRODUCTO INT NOT NULL,
    CANTIDAD SMALLINT NOT NULL CHECK(CANTIDAD > 0),
    FECHASOLICITUD DATE NOT NULL,
    FECHAFINALIZACION DATE NULL,
    COSTO MONEY NOT NULL CHECK(COSTO >= 0),
    PAGO BIT NOT NULL DEFAULT(0)    
)
GO
CREATE TABLE CLIENTES(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    APELLIDOS VARCHAR(50) not null,
    NOMBRES VARCHAR(50) NOT NULL,
    MAIL VARCHAR(200) NULL,
    TELEFONO VARCHAR(15) NULL,
    CELULAR VARCHAR(15) NULL,
    REGISTROWEB BIT NOT NULL
)
GO
CREATE TABLE PRODUCTOS(
    ID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	IDMATERIAL INT NOT NULL FOREIGN KEY REFERENCES MATERIALES (ID),
	IDCATEGORIA INT NULL FOREIGN KEY REFERENCES CATEGORIAS (ID),
    DESCRIPCION VARCHAR(100) NOT NULL,
    DIASCONSTRUCCION TINYINT NOT NULL CHECK (DIASCONSTRUCCION > 0),
    PRECIO MONEY NOT NULL,
    PVM MONEY NULL,
    CANTIDADMAYORISTA TINYINT NULL CHECK (CANTIDADMAYORISTA > 0),
	SEÑA BIT NOT NULL DEFAULT(0)
)
GO
ALTER TABLE PRODUCTOS
ADD CONSTRAINT CHK_PRECIOS CHECK(PVM < PRECIO)
GO
ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_CLIENTES FOREIGN KEY (IDCLIENTE)
REFERENCES CLIENTES(ID)
GO
ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_PRODUCTOS FOREIGN KEY (IDPRODUCTO)
REFERENCES PRODUCTOS(ID)
GO
CREATE TABLE LOCALIDADES(
	ID INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL
)
GO
CREATE TABLE ENVIOS(
	ID BIGINT NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES PEDIDOS(ID),
	FECHA_ENVIO DATE NOT NULL,
	FECHA_ENTREGA DATE NULL,
	DOMICILIO VARCHAR(50) NOT NULL,
	CP INT NOT NULL FOREIGN KEY REFERENCES LOCALIDADES(ID),
	COSTO MONEY NOT NULL
)
GO
CREATE TABLE COLABORADORES(
	LEGAJO INT NOT NULL PRIMARY KEY,
	APELLIDO VARCHAR(50) NOT NULL,
	NOMBRES VARCHAR(100) NOT NULL,
	GENERO CHAR NULL CHECK (GENERO = 'M' OR GENERO = 'F'),
	SUELDO MONEY NOT NULL,
	FECHA_INGRESO DATE NOT NULL
)
GO
CREATE TABLE COLABORADORES_X_PEDIDO(
	IDPEDIDO BIGINT NOT NULL FOREIGN KEY REFERENCES PEDIDOS(ID),
	LEGAJO INT NOT NULL FOREIGN KEY REFERENCES COLABORADORES(LEGAJO),
	IDTAREA INT NOT NULL FOREIGN KEY REFERENCES TAREAS(ID),
	PRIMARY KEY (IDPEDIDO, LEGAJO, IDTAREA)
)
GO
ALTER TABLE CLIENTES
ADD FNAC DATE NULL
