USE master
GO
DROP DATABASE PARTE1
GO
CREATE DATABASE PARTE1
GO
USE PARTE1
GO
CREATE TABLE CATEGORIAS(
	IDCATEGORIA INT NOT NULL PRIMARY KEY,
	CATEGORIA VARCHAR(50) NOT NULL
)
GO
CREATE TABLE FORMATOS(
	IDFORMATO INT NOT NULL PRIMARY KEY,
	NOMBRE_CORTO VARCHAR(5) NOT NULL,
	NOMBRE_LARGO VARCHAR(50) NOT NULL
)
GO
CREATE TABLE AUTORES(
	IDAUTOR BIGINT NOT NULL PRIMARY KEY,
	APELLIDO VARCHAR(50) NOT NULL,
	NOMBRES VARCHAR(100) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL
)
GO
CREATE TABLE LIBROS(
	IDLIBRO BIGINT NOT NULL PRIMARY KEY,
	TITULO VARCHAR(140) NOT NULL,
	PAGINAS INT NOT NULL,
	IDCATEGORIA INT NOT NULL FOREIGN KEY REFERENCES CATEGORIAS(IDCATEGORIA)
)
GO
CREATE TABLE FORMATOS_X_LIBRO(
	IDLIBRO BIGINT NOT NULL FOREIGN KEY REFERENCES LIBROS(IDLIBRO),
	IDFORMATO INT NOT NULL FOREIGN KEY REFERENCES FORMATOS(IDFORMATO),
	PRECIO MONEY NOT NULL,
	FECHA_DISPONIBLE SMALLDATETIME NOT NULL,
	PRIMARY KEY(IDLIBRO, IDFORMATO)
)
GO
CREATE TABLE AUTORES_X_LIBRO(
	IDLIBRO BIGINT NOT NULL FOREIGN KEY REFERENCES LIBROS(IDLIBRO),
	IDAUTOR BIGINT NOT NULL FOREIGN KEY REFERENCES AUTORES(IDAUTOR),
	PRIMARY KEY (IDLIBRO, IDAUTOR)	
)