--1
CREATE TRIGGER TR_NUEVA_CUENTA ON CUENTAS
AFTER INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
			-- LA CUENTA NUEVA YA FUE REGISTRADA
			
			-- ESTABLECER EL TAMAÑO REAL DE ALMACENAMIENTO DE LA CUENTA CREADA
			DECLARE @IDTIPO INT
			DECLARE @IDREFERENTE BIGINT
			DECLARE @TAMAÑO BIGINT
			DECLARE @IDCUENTA BIGINT
			
			SELECT @IDTIPO = IDTIPO, @IDREFERENTE = IDCUENTAREFERENCIA, @IDCUENTA = IDCUENTA
			FROM INSERTED
			
			SELECT @TAMAÑO = ESPACIOTOTAL FROM TIPOS_CUENTAS
			WHERE IDTIPO = @IDTIPO
			
			UPDATE CUENTAS SET ESPACIO = @TAMAÑO WHERE IDCUENTA = @IDCUENTA
						
			-- SI FUE INVITADO, BONIFICAR AL REFERENTE
			IF @IDREFERENTE IS NOT NULL BEGIN
				UPDATE CUENTAS SET ESPACIO = ESPACIO + 50 WHERE IDCUENTA = @IDREFERENTE
			END
			
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		PRINT ERROR_MESSAGE()
	END CATCH
END
--2
CREATE TRIGGER TR_NUEVO_ARCHIVO ON ARCHIVOS
AFTER INSERT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
			-- EL ARCHIVO YA FUE REGISTRADO
			
			-- VERIFICAR QUE EL TAMAÑO DEL ARCHIVO + LA SUMA DE LOS ARCHIVOS ACTUALES
			-- NO SUPERE EL TAMAÑO DE ALMACENAMIENTO DEL CLIENTE
			DECLARE @IDCUENTA BIGINT
			DECLARE @ESPACIOCUENTA BIGINT
			DECLARE @TAMAÑOACUMULADO BIGINT
			
			SELECT @IDCUENTA = IDCUENTA FROM INSERTED
			SELECT @ESPACIOCUENTA = ESPACIO FROM CUENTAS WHERE IDCUENTA = @IDCUENTA
			SELECT @TAMAÑOACUMULADO = SUM(TAMAÑO) FROM ARCHIVOS
			WHERE IDCUENTA = @IDCUENTA
			
			IF @TAMAÑOACUMULADO > @ESPACIOCUENTA BEGIN
				RAISERROR('ERROR', 16, 1)
			END
				
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		RAISERROR('LA CUENTA NO TIENE ESPACIO SUFICIENTE. COMPRE AHORA MÁS ESPACIO CON EL CYBERMONDAY', 16, 1)
	END CATCH
END