Use FABRICA

/*
1) Un listado con el código de producto, descripción del producto, precio de venta y nombre de la categoría del producto 
(sólo de los que poseen categoría de producto).
*/

/*
2) Un listado con el código de producto, descripción del producto, precio de venta y nombre de la categoría del producto 
(Todos los productos incluso los que no posean categoría de producto).
*/

/*
3) Un listado con el código de producto, descripción del producto, precio de venta y nombre de la categoría del producto 
(Todas las categorías de producto incluso las que no posean productos asociados a ellas).
*/

/*
4) Un listado con el código de producto, descripción del producto, precio de venta y nombre de la categoría del producto 
(Todos los productos y todas las categorías aunque no haya registros relacionados entre sí).
*/

/*
5) Un listado con el código de producto, descripción del producto, precio de venta y nombre del material. 
De todos los productos que pertenezcan a la categoría con nombre "Placards".
*/

/*
6) Por cada pedido con fecha de solicitud en Marzo de 2019, listar código de pedido, nombre del producto, categoría del producto, 
apellido y nombres del cliente y el costo del pedido.
*/

/*
7) Listar apellidos y nombres de todos los clientes que no hayan abonado un producto solicitado hace más de 15 días.
*/

/*
8) Listar apellido y nombres de los colaboradores que trabajaron en los pedidos 1, 2 y 3. Listarlos sin repeticiones.
*/
/*
9) Listado de pedidos que hayan sido enviados. Incluir en el listado el código de pedido, la fecha de envío, apellido y 
nombre del cliente y el domicilio de envío.
*/
/*
10) Listado de pedidos que no hayan sido enviados. Incluir en el listado el código de pedido, el costo del pedido y 
todos los datos del cliente.
*/
/*
11) Listado con los código de pedido, legajo, apellido y nombres del colaborador que hayan realizado la tarea de 'Ensamblado' en 
un producto de categoría 'Placards'.
*/
/*
12) Nombre de todos los materiales que no se hayan utilizado en ningún producto.
*/
/*
13) Todos los datos de los clientes que hayan comprado al menos un producto en Febrero de 2019.
*/
/*
14) Nombre y apellido y nombre de todas las tareas realizadas por el colaborador con Legajo número 1000. 
El listado no debe admitir registrados duplicados.
*/
/*
15) Listado de pedidos con ID, Apellido y nombre del cliente, costo de pedido, fecha de envío, domicilio de envío, costo de envío y costo total. El costo total es el costo de pedido más el costo de envío. En el listado deben figurar todos los pedidos, incluso los que no fueron enviados. El costo de envío para dichos productos será de $0.
*/