-- 1) Listado de todos los campos de todos los productos

-- 2) Listado de Apellido, nombres y mail de todos los clientes (XLS)

-- 3) Listado de los colaboradores ordenados por sueldo del mayor al menor.

-- 4) Listado de los tres colaboradores con mejor sueldo. (XLS)

-- 5) Listado de todos los campos del colaborador con legajo 1000

-- 6) Listado de todos los productos cuyo precio de venta sea mayor a 5000

-- 7) Listado de los apellidos y nombres de los clientes y su año de nacimiento.

-- 7) Listado todos los pedidos incluyendo la demora (en días) de la finalización del producto. (XLS)

-- 8) Listado de los apellidos y nombres de los clientes que se hayan registrado a través de la web y que hayan nacido
-- después del año 1990.

-- 9) Listado de los productos cuya construcción pueda hacerse en 2 días o su precio sea mayor a 8000. (XLS)

-- 10) Listado de todos los productos cuyo precio de venta se encuentre entre 3000 y 7000. (XLS)

-- 11) Listado de todos los clientes cuya fecha de nacimiento sea entre '1/1/1990' y '2/2/1991'

-- 12) Todos los pedidos de los clientes con ID 1, 2 y 9

-- 13) Todos los pedidos de los clientes que no tengan el ID (3, 5 y 9) (XLS)

-- 14) Todos los clientes que tengan mail

-- 15) Todos los clientes que tengan mail pero no celular (XLS)

-- 16) Todos los clientes cuyo apellido finalice con el texto 'EZ'

-- 17) Todos los clientes cuyo apellido contenga el texto 'EZ'

-- 18) Todos los colaboradores cuyo nombre comience con 'A'

-- 19) Todos los colaboradores cuyo nombre comience con vocal

-- 20) Todos los colaboradores cuyo nombre no comience con vocal

-- 21) Todos lo colaboradores cuyo apellido contenga un espacio en su tercer caracter

-- 22) Apellido y nombres de los clientes y una columna con un dato de contacto en el siguiente orden de prioridad: Mail, Telefono, Celular. (XLS)