CREATE DATABASE FABRICA
GO
USE FABRICA
GO
CREATE TABLE PEDIDOS(
	ID BIGINT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	IDCLIENTE INT NOT NULL,
	IDPRODUCTO INT NOT NULL,
	CANTIDAD SMALLINT NOT NULL CHECK(CANTIDAD > 0),
	FECHASOLICITUD DATE NOT NULL,
	FECHAFINALIZACION DATE NULL,
	COSTO MONEY NOT NULL CHECK(COSTO >= 0),
	PAGO BIT NOT NULL DEFAULT(0)	
)

ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_CLIENTES FOREIGN KEY (IDCLIENTE)
REFERENCES CLIENTES(ID)

ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_PRODUCTOS FOREIGN KEY (IDPRODUCTO)
REFERENCES PRODUCTOS(ID)


CREATE TABLE CLIENTES(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	APELLIDOS VARCHAR(50) not null,
	NOMBRES VARCHAR(50) NOT NULL,
	MAIL VARCHAR(200) NULL,
	TELEFONO VARCHAR(15) NULL,
	CELULAR VARCHAR(15) NULL,
	REGISTROWEB BIT NOT NULL
)

CREATE TABLE PRODUCTOS(
	ID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	DESCRIPCION VARCHAR(100) NOT NULL,
	DIASCONSTRUCCION TINYINT NOT NULL CHECK (DIASCONSTRUCCION > 0),
	PRECIO MONEY NOT NULL,
	PVM MONEY NULL,
	CANTIDADMAYORISTA TINYINT NULL CHECK (CANTIDADMAYORISTA > 0)
)

ALTER TABLE PRODUCTOS
ADD CONSTRAINT CHK_PRECIOS CHECK(PVM < PRECIO)