--USE MASTER
--GO
--DROP DATABASE BANCO
--GO
CREATE DATABASE BANCO
GO
USE BANCO
GO
CREATE TABLE CLIENTES(
	IDCLIENTE BIGINT NOT NULL PRIMARY KEY,
	APELLIDO VARCHAR(50) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	ESTADO BIT NOT NULL
)
GO
CREATE TABLE CUENTAS(
	IDCUENTA BIGINT NOT NULL PRIMARY KEY,
	IDCLIENTE BIGINT NOT NULL FOREIGN KEY REFERENCES CLIENTES (IDCLIENTE),
	TIPO VARCHAR(2) NOT NULL CHECK (TIPO IN ('CA','CC')), -- 'CA' CAJA DE AHORRO , 'CC'  CUENTA CORRIENTE
	LIMITE MONEY NOT NULL,
	SALDO MONEY NOT NULL,
	ESTADO BIT NOT NULL
)
GO
ALTER TABLE CUENTAS
ADD CONSTRAINT CHK_SALDO CHECK (SALDO >= LIMITE)
GO
CREATE TABLE TARJETAS(
	IDTARJETA BIGINT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	IDCUENTA BIGINT NOT NULL FOREIGN KEY REFERENCES CUENTAS (IDCUENTA),
	TIPO CHAR NOT NULL CHECK (TIPO IN ('D', 'C')), -- D DEBITO, C CREDITO
	ESTADO BIT NOT NULL
)
GO
CREATE TABLE MOVIMIENTOS(
	IDMOVIMIENTO BIGINT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	IDCUENTA BIGINT NOT NULL FOREIGN KEY REFERENCES CUENTAS (IDCUENTA),
	IMPORTE MONEY NOT NULL CHECK (IMPORTE > 0),
	TIPO CHAR NOT NULL CHECK (TIPO IN ('D', 'C')), -- D DEBITO, C CREDITO
	FECHA SMALLDATETIME NOT NULL,
	ESTADO BIT NOT NULL DEFAULT(1)
)
GO
CREATE TABLE TRANSFERENCIAS(
	IDTRANSFERENCIA BIGINT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	ORIGEN BIGINT NOT NULL FOREIGN KEY REFERENCES CUENTAS (IDCUENTA),
	DESTINO BIGINT NOT NULL FOREIGN KEY REFERENCES CUENTAS (IDCUENTA),
	IMPORTE MONEY NOT NULL CHECK (IMPORTE > 0),
	FECHA SMALLDATETIME NOT NULL,
	ESTADO BIT NOT NULL DEFAULT(1)
)

-- CLIENTES
INSERT INTO CLIENTES (IDCLIENTE, APELLIDO, NOMBRE, ESTADO) VALUES (1, 'SEINFELD', 'JERRY', 1)
INSERT INTO CLIENTES (IDCLIENTE, APELLIDO, NOMBRE, ESTADO) VALUES (2, 'COSTANZA', 'GEORGE', 1)
INSERT INTO CLIENTES (IDCLIENTE, APELLIDO, NOMBRE, ESTADO) VALUES (3, 'BENES', 'ELAINE', 1)
INSERT INTO CLIENTES (IDCLIENTE, APELLIDO, NOMBRE, ESTADO) VALUES (4, 'KRAMER', 'COSMO', 1)

-- CUENTAS
INSERT INTO CUENTAS (IDCUENTA, IDCLIENTE, TIPO, SALDO, LIMITE, ESTADO)
VALUES (1, 1, 'CA', 1000, 0, 1)
INSERT INTO CUENTAS (IDCUENTA, IDCLIENTE, TIPO, SALDO, LIMITE, ESTADO)
VALUES (2, 2, 'CC', 0, -5000, 1)
INSERT INTO CUENTAS (IDCUENTA, IDCLIENTE, TIPO, SALDO, LIMITE, ESTADO)
VALUES (3, 3, 'CA', 0, 0, 1)
INSERT INTO CUENTAS (IDCUENTA, IDCLIENTE, TIPO, SALDO, LIMITE, ESTADO)
VALUES (4, 4, 'CC', 0, -1000, 1)