--3) Los clientes que no realizaron ningún pedido en Febrero de 2019. 

--4) Los productos que tengan un precio de venta mayor al precio de venta promedio. 

--5) Todos los datos de los productos cuyo precio de venta sea mayor a cualquier producto cuyo nombre de material sea "Pino".

--8) Por cada cliente, listar el apellido y nombre y la cantidad de pedidos realizados de productos que requieran seña y la cantidad de pedidos realizados de productos que no requieran seña.

--10) Apellido y nombres de los clientes que hayan realizado más pedidos de productos que requieren seña que pedidos que no requieren seña.

--13) El porcentaje de facturación de los pedidos realizados en Febrero de 2019 con respecto al total facturado.